# 测试 以秒为时间
TESTER_CYCLE = 60
# 爬取
GETTER_CYCLE = 30
# 开启测试和获取函数
TESTER_ENABLED = True
GETTER_ENABLED = True

# 最大分和最小分以及初始分数
MAX_SCORE = 10
MIN_SCORE = 0
INITIAL_SCORE = 5

BATCH_TEST_SIZE = 100
VALID_STATUS_CODES = [200]
TEST_URL = 'http://www.baidu.com'
POOL_UPPER_THRESHOLD = 500
