# 按秒 测试按照一天
TESTER_CYCLE = 60
# 每天爬取一次
GETTER_CYCLE = 24
# 开启测试和获取函数
TESTER_ENABLED = True
GETTER_ENABLED = True

# 最大分和最小分以及初始分数
MAX_SCORE = 10
MIN_SCORE = 0
INITIAL_SCORE = 5

BATCH_TEST_SIZE = 10
VALID_STATUS_CODES = [200]
TEST_URL = 'http://www.baidu.com'
POOL_UPPER_THRESHOLD = 500
